version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # You can adjust the Python version if needed

    steps:
      - checkout

      - run:
          name: Install Python and pip
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt

      # Optional: If you want to skip tests, you can comment this out
      # - run:
      #     name: Run tests
      #     command: |
      #       . venv/bin/activate
      #       pytest

      - run:
          name: Deploy
          command: |
            . venv/bin/activate
            # Add your deployment commands here

      - run:
          name: Deploy to Railway
          command: |
            curl -fsSL https://cli.railway.app | bash
            railway login --token e66cfacd-0a91-462b-9ca3-0b8f2324ff9b
            railway up --detach



workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
